import { taskWsBindings } from "./task";

/**
 * Returns the flat list of all Socket.IO event names that WebSocketProvider
 * should bind a routeEvent handler to.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export function getAllWsBindings(): string[] {
  return [
  ...taskWsBindings,
  ];
}
