// Socket.IO event bindings for the Task domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Every string here must match the event name the backend emits via socket.emit().
// WebSocketProvider loops over getAllWsBindings() and registers routeEvent() for each.

export const taskWsBindings: string[] = [
  "task.created",
  "task.updated",
  "task.deleted",
  "task.assigned",
  "task.priority-changed",
];
