import { QueryClient } from "@tanstack/react-query";

import { taskDispatchers } from "./task";

type AnyPayload = Record<string, unknown> | null | undefined;

/**
 * Flat event-name → handler map.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const domainDispatchers: Record<
  string,
  (payload: AnyPayload, queryClient: QueryClient) => void
> = {
  ...taskDispatchers,
};
