import { QueryClient } from "@tanstack/react-query";
import {
  applyTaskAssigned,
  applyTaskCreated,
  applyTaskDeleted,
  applyTaskPriorityChanged,
  applyTaskUpdated,
} from "../../projections/task-projections";
import { getFailureMode } from "../../failure-mode";
import { taskKeys } from "../../query-keys/task";
import { emitLocalTrace, getTraceContextInfo } from "../../trace-client";

type AnyPayload = Record<string, unknown> | null | undefined;

function withoutMeta(payload: Record<string, unknown>) {
  const { _meta, ...entityPayload } = payload;
  return entityPayload;
}

function applyDirectCacheBypass(
  payload: Record<string, unknown>,
  queryClient: QueryClient,
): readonly unknown[] | null {
  const projectId = payload.projectId as string | undefined;
  const taskId = payload.taskId as string | undefined;
  if (!projectId || !taskId) {
    return null;
  }

  const listKey = taskKeys.list({ projectId });
  queryClient.setQueryData<Record<string, unknown>[]>(listKey, (current) => {
    const next = Array.isArray(current) ? current : [];
    return [
      ...next,
      {
        id: `direct-${taskId}`,
        ...withoutMeta(payload),
        _bypassed: true,
      },
    ];
  });

  return listKey;
}

// Dispatch map for the Task domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Add an entry for every event the domain emits. The key must be the exact
// event name string (dot notation). The value calls into the domain projection.

export const taskDispatchers: Record<
  string,
  (payload: AnyPayload, queryClient: QueryClient) => void
> = {
  "task.created": (payload, queryClient) => {
    if (!payload) {
      return;
    }

    const payloadRecord = payload as Record<string, unknown>;
    const traceContext = getTraceContextInfo("task.created", payloadRecord);

    emitLocalTrace({
      stage: "dispatcher",
      domain: traceContext.domain,
      eventName: "task.created",
      correlationId: traceContext.correlationId,
      session: traceContext.session,
      payload: traceContext.payload,
      status: "ok",
      detail: "task.created mapped to domain dispatcher",
    });

    const activeFailureMode = getFailureMode();
    if (activeFailureMode === "skip-projection") {
      emitLocalTrace({
        stage: "projection",
        domain: traceContext.domain,
        eventName: "task.created",
        correlationId: traceContext.correlationId,
        session: traceContext.session,
        payload: traceContext.payload,
        status: "skipped",
        detail: "projection suppressed by failure injector",
        failureMode: "skip-projection",
      });
      return;
    }

    if (activeFailureMode === "direct-cache-mutation") {
      const listKey = applyDirectCacheBypass(payloadRecord, queryClient);
      emitLocalTrace({
        stage: "projection",
        domain: traceContext.domain,
        eventName: "task.created",
        correlationId: traceContext.correlationId,
        session: traceContext.session,
        payload: traceContext.payload,
        status: "error",
        detail: "BYPASS DETECTED",
        failureMode: "direct-cache-mutation",
      });
      emitLocalTrace({
        stage: "cache-write",
        domain: traceContext.domain,
        eventName: "task.created",
        correlationId: traceContext.correlationId,
        session: traceContext.session,
        payload: traceContext.payload,
        status: "error",
        detail: `direct setQueryData ${JSON.stringify(listKey)}`,
        failureMode: "direct-cache-mutation",
      });
    }

    applyTaskCreated(payloadRecord, queryClient);
  },
  "task.updated": (payload, queryClient) => {
    if (!payload) {
      return;
    }

    const payloadRecord = payload as Record<string, unknown>;
    const traceContext = getTraceContextInfo("task.updated", payloadRecord);

    emitLocalTrace({
      stage: "dispatcher",
      domain: traceContext.domain,
      eventName: "task.updated",
      correlationId: traceContext.correlationId,
      session: traceContext.session,
      payload: traceContext.payload,
      status: "ok",
      detail: "task.updated mapped to domain dispatcher",
    });

    applyTaskUpdated(payloadRecord, queryClient);
  },
  "task.deleted": (payload, queryClient) => {
    if (!payload) {
      return;
    }

    const payloadRecord = payload as Record<string, unknown>;
    const traceContext = getTraceContextInfo("task.deleted", payloadRecord);

    emitLocalTrace({
      stage: "dispatcher",
      domain: traceContext.domain,
      eventName: "task.deleted",
      correlationId: traceContext.correlationId,
      session: traceContext.session,
      payload: traceContext.payload,
      status: "ok",
      detail: "task.deleted mapped to domain dispatcher",
    });

    applyTaskDeleted(payloadRecord, queryClient);
  },
  "task.assigned": (payload, queryClient) => {
    if (!payload) {
      return;
    }

    const payloadRecord = payload as Record<string, unknown>;
    const traceContext = getTraceContextInfo("task.assigned", payloadRecord);

    emitLocalTrace({
      stage: "dispatcher",
      domain: traceContext.domain,
      eventName: "task.assigned",
      correlationId: traceContext.correlationId,
      session: traceContext.session,
      payload: traceContext.payload,
      status: "ok",
      detail: "task.assigned mapped to domain dispatcher",
    });

    applyTaskAssigned(payloadRecord, queryClient);
  },
  "task.priority-changed": (payload, queryClient) => {
    if (!payload) {
      return;
    }

    const payloadRecord = payload as Record<string, unknown>;
    const traceContext = getTraceContextInfo(
      "task.priority-changed",
      payloadRecord,
    );

    emitLocalTrace({
      stage: "dispatcher",
      domain: traceContext.domain,
      eventName: "task.priority-changed",
      correlationId: traceContext.correlationId,
      session: traceContext.session,
      payload: traceContext.payload,
      status: "ok",
      detail: "task.priority-changed mapped to domain dispatcher",
    });

    applyTaskPriorityChanged(payloadRecord, queryClient);
  },
};
