import { z } from "zod";

import { taskSchemas } from "./task";

// Base envelope/actor/context/origin schemas and their types
export {
  EventActorSchema,
  EventContextSchema,
  EventOriginSchema,
  EventEnvelopeSchema,
  type EventActor,
  type EventContext,
  type EventOrigin,
  type EventEnvelope,
} from "./_base";

/**
 * Merged payload schema map — every event type registered across all domain slices.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const EventPayloadSchemas: Record<string, z.ZodTypeAny> = {
  ...taskSchemas,
};
