import { z } from "zod";

// Task event payload schemas
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Each key corresponds to an event name you pass to EventFactory.publish().
// The matching .strict() Zod schema is validated at publish time.
// If you add a field here, add it to your EventFactory.publish() call too.

const stringId = z.string().min(1);
const visibilitySchema = z.enum(["PUBLIC", "PRIVATE"]);

export const taskSchemas: Record<string, z.ZodTypeAny> = {
  "task.created": z
    .object({
      taskId: stringId,
      title: z.string().min(1),
      projectId: stringId,
      creatorId: stringId,
      visibility: visibilitySchema,
      status: z.string().min(1),
      priority: z.string().min(1),
      clientTempId: z.string().min(1).nullable(),
      assigneeId: stringId.nullable(),
    })
    .strict(),
  "task.updated": z
    .object({
      taskId: stringId,
      title: z.string().min(1),
      projectId: stringId,
      creatorId: stringId,
      visibility: visibilitySchema,
      status: z.string().min(1),
      priority: z.string().min(1),
      clientTempId: z.string().min(1).nullable(),
      assigneeId: stringId.nullable(),
    })
    .strict(),
  "task.deleted": z
    .object({
      taskId: stringId,
      projectId: stringId,
      creatorId: stringId,
      visibility: visibilitySchema,
      status: z.string().min(1),
      priority: z.string().min(1),
    })
    .strict(),
  "task.assigned": z
    .object({
      taskId: stringId,
      projectId: stringId,
      assigneeId: stringId,
    })
    .strict(),
  "task.priority-changed": z
    .object({
      taskId: stringId,
      projectId: stringId,
      priority: z.string().min(1),
    })
    .strict(),
};
