import { taskProjections } from "./task";

// Shared types — re-exported so consumers only import from this barrel
export type {
  QueryKey,
  ProjectionFn,
  EntityProjectionEntry,
} from "./_types";

/**
 * Registry of all entity projections across all domains.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export const ENTITY_PROJECTIONS: Record<string, import("./_types").EntityProjectionEntry> = {
  ...taskProjections,
};
