import type { EntityProjectionEntry } from "./_types";

// Entity projection registry for the Task domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Keys must match what taskKeys.list({ projectId }) returns:
//   ["tasks", "list", projectId]

export const taskProjections: Record<string, EntityProjectionEntry> = {
  task: {
    ownedKeyFactories: ["taskKeys"],
    onCreate: {
      required: [
        (_entity, context) => [
          "tasks",
          "list",
          ((context as Record<string, unknown>)?.projectId as string) ?? "",
        ],
      ],
      invalidate: [],
    },
    onUpdate: {
      required: [
        (_entity, context) => [
          "tasks",
          "list",
          ((context as Record<string, unknown>)?.projectId as string) ?? "",
        ],
        (entity) => [
          "tasks",
          "detail",
          String((entity as Record<string, unknown>).id ?? ""),
        ],
      ],
      invalidate: [],
    },
    onDelete: { invalidate: [] },
  },
};
