/**
 * Centralized query-keys barrel — re-exports all domain key factories.
 * Generated by rivergen init and regenerated atomically by rivergen gen.
 * DO NOT hand-edit — your changes will be overwritten.
 */
export * from "./task";
