// Query key factory for the Task domain.
// Generated by rivergen gen. Edit freely — regenerateBarrel() never touches this file.
//
// Import via: import { taskKeys } from "@/lib/query-keys"
// These factories are the ONLY way to reference this entity's cache scope.
// Hardcoding ["tasks", ...] strings anywhere else is a Gate #10 violation.
// list() scope mirrors room template: project:${projectId}

export const taskKeys = {
  all: () => ["tasks"] as const,
  list: (ctx: { projectId: string }) => ["tasks", "list", ctx.projectId] as const,
  detail: (id: string) => ["tasks", "detail", id] as const,
};
